# lab8
Q1:
ANS: because there's no "catch" to catch the throw, and it leads to the termination of the program 

Q2: 
ANS:
no， it will cause a core dumped 
we need to change the float to double 
or the terminate called after throwing an instance of 'double' 

Q3:
SEE the program 
i have changed the getMino.cpp 內容 with "new"
others are like the lab7
